### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zularizal** [shyam-s00/Android-Notes#1]
Hi @shyam-s00 , I'm a graphic designer, after I review your project, I'm interested in your project and I want to contribute by creating a logo/icon for your project. What do you think?

**Comment by shyam-s00** [comment]
Why not? If you'd like to...

**Comment by zularizal** [comment]
Hi, this is the logo and icons that I designed for you, what do you think?

If something wants to be changed, let me know.

![logo](https://user-images.githubusercontent.com/38547278/45272747-4eef2b00-b4d9-11e8-9e3e-dcd8d82faf99.png)

**Comment by shyam-s00** [comment]
this is cool man. Really nice. Since we are doing for android colors/themes will be picked based on the material design.  It'd be nice if these match the material colors.  You can refer here: https://material.io/design/color/the-color-system.html#

**Comment by zularizal** [comment]
In the logo I use material color. Do you want the logo in material design style?

What color do you like?

![rect2532](https://user-images.githubusercontent.com/38547278/45338417-4a00a900-b5b7-11e8-9d1c-3888203066dd.png)

**Comment by shyam-s00** [comment]
![screenshot_android_notes_20180911-215312](https://user-images.githubusercontent.com/8418806/45373662-a1c9ff00-b60d-11e8-9247-82f588b9113b.png)
Material blue would be nice

**Comment by zularizal** [comment]
I adjust the color of the logo with the main color of your application. The color name is indigo (#3f51b5ff). do you like that color?

![21](https://user-images.githubusercontent.com/38547278/45395097-a79c0080-b65e-11e8-8efa-506a50edcc23.png)

**Comment by shyam-s00** [comment]
This is nice. That shadow effect is cool. Just one correction, make the tip of the pencil white too. It's perfectly normal for icons to be bi color.

**Comment by zularizal** [comment]
Okay, if there is no more I will send a pull request to you

![21](https://user-images.githubusercontent.com/38547278/45395482-7e7c6f80-b660-11e8-83fa-b5dad603e204.png)

**Comment by shyam-s00** [comment]
Yep... perfect

**Comment by zularizal** [comment]
Hi, I have sent a pull request to you. #2 

And also I have uploaded your logo to the drive, you can find the logo vector. If you want to apply the adaptive icon to your application, you can download the .svg file on the drive.

https://drive.google.com/open?id=1dkVsGDMB0V-1jXWWQEIbWqbXyOzaUzy9
